### ISSUE TITLE
airi-0.0.1.tar.gz cannot be extracted successfully on OSX and Windows

### ISSUE THREAD

**Issue by srid** [manuelnaranjo/AIRi#1]
See https://github.com/ActiveState/applib/issues/#issue/11

**Comment by manuelnaranjo** [comment]
Is this some sort of autogenerated bug report?

**Comment by srid** [comment]
No, it was manually reported by me.

**Comment by manuelnaranjo** [comment]
Ohh ok great, I was on vacations and got this email and didn't know what to do with it.

OSX might never be supported I need to get pybluez compiled for it and I don't have the tools for that. Windows will be supported soon, still I don't get what's the procedure you're following here.

**Comment by srid** [comment]
> I don't get what's the procedure you're following here.

I noticed this error when building new PyPI packages in PyPM; see http://code.activestate.com/pypm/airi/

```
$ wget http://pypi.python.org/packages/source/a/airi/airi-0.0.1.tar.gz
$ tar zxf airi-0.0.1.tar.gz 
airi-0.0.1/AIRi: Can't remove already-existing dir: Directory not empty
tar: Error exit delayed from previous errors.
$
```

A related error broke our backend builder, so I added airi to the blacklist for osx/windows.
